crowdsourcemedical/volunteer-database

.github/workflows/backend.yml
.github/workflows/frontend.yml
README.md
backend/requirements.txt
frontend/src/App.test.js

This will add a GitHub action that verifies that all (none yet) backend and (only 1 fake one) frontend tests pass on any push to the master branch and any open pull request.
These are useful for:
1. Being a source of truth for how things should run, removing FUD around environment discrepancies
1. Make sure dependencies are tracked correctly
1. Make sure the tests still pass

Add GitHub action for verifying changes

---

environ.sh

Added a script for Linux, to rapidly set up environments. Will need further updating. Script must be run using sudo.

Added Environment Setup Script Linux

---

frontend/src/App.js
frontend/src/components/Forms/checkboxSection.js
frontend/src/pages/newproject.js
frontend/src/pages/storybook.js

Wireframe done. Need to add Form handling when more details on this are available. Created checkbox component . Please go easy on me pretty new to react :) any tips would be appreciated.

Weeksi dev

---

frontend/package.json
frontend/public/index.html
frontend/src/App.js
frontend/src/components/Cards/userSmallCard.js
frontend/src/components/header.js
frontend/src/pages/signup.js
frontend/src/pages/signup_project.js
frontend/src/pages/signup_volunteer.js
frontend/yarn.lock

[WIP] Signup page

---

README.md

add information about PR review process to readme file.
Safe to merge / deploy, no blockers

Update readme with PR process information

---

.gitignore
frontend/src/pages/login.js

Relevant task: https://trello.com/c/rwgqHJPm/3-setup-login-page

Login page

---

frontend/src/index.js
frontend/src/styles/theme.js

Added a MUI (Material-UI) theme template file (`src/styles/theme.js`) which will keep the project's color scheme/palette uniform.
The theme was then applied to the entire App component in `index.js` so that all children components will be impacted by the same color theme.
Colors are not set in stone and based on what is currently being used in the Figma design.
More details regarding the MUI theme can be found at:
https://material-ui.com/customization/theming/
https://material-ui.com/styles/advanced/

Adding MUI global themes

---

frontend/src/environment.js
frontend/src/helpers/api.js

This is a WIP. Haven't been able to test since I'm having trouble running Docker on Windows. Going to try to get that working now then continue testing / building it out. Feel free to take a look and give me feedback

Creates api helper class and environment file

---

frontend/src/App.js

Double check if it's all fine!

Added UserProfile to acceess the component from the App.js

---

frontend/src/pages/style.js
frontend/src/styles/theme.js
frontend/yarn.lock

Added the remainder of the heading styles, as well as the text primary and secondary colors.
An object `colors` has added with the color values so there is a single source to alter changes in the future.

Remainder of theme headings; text primary and secondary added

---

README.md

The goal here is to improve development workflows, processes, communication, and onboarding new people.

Improves the README.md

---

frontend/src/pages/footer.js
frontend/src/styles/theme.js

Hey guys - made a quick mockup for the footer components...see below

Mockup for footer component

---

frontend/src/components/Forms/LoginForm.js
frontend/src/components/navbar.js

Currently it's purple but here it is back to the blue

Changed Login dialog backdrop and form colors to the correct blue from theme

---

backend/Makefile
backend/app/database.py
backend/app/main.py
backend/app/tests/conftest.py
backend/app/tests/test_crud.py
backend/app/tests/test_main.py
backend/pytest.ini
backend/tests/unit/test_simple.py

- Updated Makefile to tell pytest to not capture output
- Updated Makefile to set env var for running tests
- Updated database.py to connect to an in-memory DB for tests
- Removed comment from main.py
- Moved test files to new directory
- Implemented fixtures to enable testing
- Added tests

Enabling unit and functional testing of API

---

frontend/src/pages/footer.js

Small edit to centre align the copywrite in the footer

Centre align Copywrite in footer

---

frontend/src/pages/footer.js
frontend/src/styles/colors.js
frontend/src/styles/theme.js

I need access to the color pallet for the background in the footer - so refactored it out into its own file.

Refactor colors out into their own file

---

frontend/.eslintrc.js
frontend/package-lock.json
frontend/package.json

Adding AirBnb ESlint formatting to dev dependencies
1. Go to this branch
2. `npm i` (maybe need to remove the `/node_modules` folder as there is lots of mess in there)
3. `eslint src/path/to/file` or to auto fix problems then run `eslint src/path/to/file --fix`
4. If using VSCode, then enable the [ESlint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
Also `node_modules`/`package_lock.json` is a mess - so I reinstalled them.

Adding ESlint code formatting

---

frontend/.eslintrc.js
frontend/src/components/Profile/Card-Project.component.jsx
frontend/src/components/Profile/Profile.component.jsx
frontend/src/components/navbar.jsx

* Changed line length to be 120 (think this is suitable over 100)
* Tidy up other files

The final ESLint fixes - nice and tidy

---

backend/app/models.py
backend/scripts/psql.bat
backend/scripts/psql.sh
backend/scripts/readme.md
scripts/docker-rebuild.bat
scripts/docker-rebuild.sh

Also added some scripts for ease of use

Added Volunteers table which inherits from users

---

backend/Makefile
docker-compose.yml

This ensures that the names can be referenced consistently

Name Docker containers and images

---

frontend/src/components/Header.jsx

Placeholder code for when you login and it will display your avatar instead of the login button.

Placeholder to toggle avatar if logged in

---

backend/app/models.py

Nate io/position model

---

backend/alembic.ini
backend/alembic/env.py
backend/app/database.py
backend/scripts/psql.bat
backend/scripts/psql.sh
backend/scripts/pytest.bat
backend/scripts/readme.md
docker-compose.yml

Added script for running pytest from windows w/o make

Switched CSM with CSS for everything backend

---

frontend/src/pages/home.jsx

Ok first off this is not perfect but it is a step in the right direction!
* Now written using Material UI components
* Somewhat reactive to screen sizes
* There are a few things that need touching up like image opacity and box-shadow below.

Rewrite the homepage to be reactive

---

frontend/src/pages/home.jsx

Homepage Mobile
I ended up making more styling pages than necessary to better match the mockups for larger screen sizes as well.
Trello Card: https://trello.com/c/IkBf0NhT

Mobile Homepage + some larger screen styling changes to match mocks
